begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|parser
operator|.
name|chm
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Arrays
import|;
end_import

begin_import
import|import
name|junit
operator|.
name|framework
operator|.
name|Assert
import|;
end_import

begin_import
import|import
name|junit
operator|.
name|framework
operator|.
name|TestCase
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|detect
operator|.
name|TestContainerAwareDetector
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|io
operator|.
name|TikaInputStream
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|parser
operator|.
name|chm
operator|.
name|accessor
operator|.
name|ChmDirectoryListingSet
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|parser
operator|.
name|chm
operator|.
name|accessor
operator|.
name|ChmItsfHeader
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|parser
operator|.
name|chm
operator|.
name|accessor
operator|.
name|ChmItspHeader
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|parser
operator|.
name|chm
operator|.
name|accessor
operator|.
name|ChmLzxcControlData
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|parser
operator|.
name|chm
operator|.
name|core
operator|.
name|ChmCommons
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|parser
operator|.
name|chm
operator|.
name|core
operator|.
name|ChmConstants
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|parser
operator|.
name|chm
operator|.
name|lzx
operator|.
name|ChmLzxState
import|;
end_import

begin_class
specifier|public
class|class
name|TestChmLzxState
extends|extends
name|TestCase
block|{
specifier|private
name|ChmLzxState
name|chmLzxState
decl_stmt|;
specifier|private
name|int
name|windowSize
decl_stmt|;
specifier|public
name|void
name|setUp
parameter_list|()
throws|throws
name|Exception
block|{
try|try
block|{
name|TikaInputStream
name|stream
init|=
name|TikaInputStream
operator|.
name|get
argument_list|(
name|TestContainerAwareDetector
operator|.
name|class
operator|.
name|getResource
argument_list|(
name|TestParameters
operator|.
name|chmFile
argument_list|)
argument_list|)
decl_stmt|;
name|byte
index|[]
name|data
init|=
name|TestUtils
operator|.
name|toByteArray
argument_list|(
name|stream
argument_list|)
decl_stmt|;
comment|/* Creates and parses itsf header */
name|ChmItsfHeader
name|chmItsHeader
init|=
operator|new
name|ChmItsfHeader
argument_list|()
decl_stmt|;
name|chmItsHeader
operator|.
name|parse
argument_list|(
name|Arrays
operator|.
name|copyOfRange
argument_list|(
name|data
argument_list|,
literal|0
argument_list|,
name|ChmConstants
operator|.
name|CHM_ITSF_V3_LEN
operator|-
literal|1
argument_list|)
argument_list|,
name|chmItsHeader
argument_list|)
expr_stmt|;
comment|/* Creates and parses itsp block */
name|ChmItspHeader
name|chmItspHeader
init|=
operator|new
name|ChmItspHeader
argument_list|()
decl_stmt|;
name|chmItspHeader
operator|.
name|parse
argument_list|(
name|Arrays
operator|.
name|copyOfRange
argument_list|(
name|data
argument_list|,
operator|(
name|int
operator|)
name|chmItsHeader
operator|.
name|getDirOffset
argument_list|()
argument_list|,
operator|(
name|int
operator|)
name|chmItsHeader
operator|.
name|getDirOffset
argument_list|()
operator|+
name|ChmConstants
operator|.
name|CHM_ITSP_V1_LEN
argument_list|)
argument_list|,
name|chmItspHeader
argument_list|)
expr_stmt|;
comment|/* Creating instance of ChmDirListingContainer */
name|ChmDirectoryListingSet
name|chmDirListCont
init|=
operator|new
name|ChmDirectoryListingSet
argument_list|(
name|data
argument_list|,
name|chmItsHeader
argument_list|,
name|chmItspHeader
argument_list|)
decl_stmt|;
name|int
name|indexOfControlData
init|=
name|ChmCommons
operator|.
name|indexOf
argument_list|(
name|chmDirListCont
operator|.
name|getDirectoryListingEntryList
argument_list|()
argument_list|,
name|ChmConstants
operator|.
name|CONTROL_DATA
argument_list|)
decl_stmt|;
name|int
name|indexOfResetTable
init|=
name|ChmCommons
operator|.
name|indexOfResetTableBlock
argument_list|(
name|data
argument_list|,
name|ChmConstants
operator|.
name|LZXC
operator|.
name|getBytes
argument_list|()
argument_list|)
decl_stmt|;
name|byte
index|[]
name|dir_chunk
init|=
literal|null
decl_stmt|;
if|if
condition|(
name|indexOfResetTable
operator|>
literal|0
condition|)
block|{
name|dir_chunk
operator|=
name|Arrays
operator|.
name|copyOfRange
argument_list|(
name|data
argument_list|,
name|indexOfResetTable
argument_list|,
name|indexOfResetTable
operator|+
name|chmDirListCont
operator|.
name|getDirectoryListingEntryList
argument_list|()
operator|.
name|get
argument_list|(
name|indexOfControlData
argument_list|)
operator|.
name|getLength
argument_list|()
argument_list|)
expr_stmt|;
block|}
name|ChmLzxcControlData
name|clcd
init|=
operator|new
name|ChmLzxcControlData
argument_list|()
decl_stmt|;
name|clcd
operator|.
name|parse
argument_list|(
name|dir_chunk
argument_list|,
name|clcd
argument_list|)
expr_stmt|;
name|windowSize
operator|=
operator|(
name|int
operator|)
name|clcd
operator|.
name|getWindowSize
argument_list|()
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|IOException
name|e
parameter_list|)
block|{
name|e
operator|.
name|printStackTrace
argument_list|()
expr_stmt|;
block|}
block|}
specifier|public
name|void
name|testChmLzxStateConstructor
parameter_list|()
block|{
name|chmLzxState
operator|=
operator|new
name|ChmLzxState
argument_list|(
name|windowSize
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertNotNull
argument_list|(
name|chmLzxState
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testToString
parameter_list|()
block|{
if|if
condition|(
name|chmLzxState
operator|==
literal|null
condition|)
name|testChmLzxStateConstructor
argument_list|()
expr_stmt|;
name|Assert
operator|.
name|assertTrue
argument_list|(
name|chmLzxState
operator|.
name|toString
argument_list|()
operator|.
name|length
argument_list|()
operator|>
literal|20
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|tearDown
parameter_list|()
throws|throws
name|Exception
block|{ 	}
block|}
end_class

end_unit

