begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|example
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|InputStream
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|Tika
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|detect
operator|.
name|CompositeDetector
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|detect
operator|.
name|Detector
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|metadata
operator|.
name|Metadata
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|mime
operator|.
name|MediaType
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|mime
operator|.
name|MimeTypesFactory
import|;
end_import

begin_class
specifier|public
class|class
name|AdvancedTypeDetector
block|{
specifier|public
specifier|static
name|String
name|detectWithCustomConfig
parameter_list|(
name|String
name|name
parameter_list|)
throws|throws
name|Exception
block|{
name|String
name|config
init|=
literal|"/org/apache/tika/mime/tika-mimetypes.xml"
decl_stmt|;
name|Tika
name|tika
init|=
operator|new
name|Tika
argument_list|(
name|MimeTypesFactory
operator|.
name|create
argument_list|(
name|config
argument_list|)
argument_list|)
decl_stmt|;
return|return
name|tika
operator|.
name|detect
argument_list|(
name|name
argument_list|)
return|;
block|}
specifier|public
specifier|static
name|String
name|detectWithCustomDetector
parameter_list|(
name|String
name|name
parameter_list|)
throws|throws
name|Exception
block|{
name|String
name|config
init|=
literal|"/org/apache/tika/mime/tika-mimetypes.xml"
decl_stmt|;
name|Detector
name|detector
init|=
name|MimeTypesFactory
operator|.
name|create
argument_list|(
name|config
argument_list|)
decl_stmt|;
name|Detector
name|custom
init|=
operator|new
name|Detector
argument_list|()
block|{
specifier|private
specifier|static
specifier|final
name|long
name|serialVersionUID
init|=
operator|-
literal|5420638839201540749L
decl_stmt|;
specifier|public
name|MediaType
name|detect
parameter_list|(
name|InputStream
name|input
parameter_list|,
name|Metadata
name|metadata
parameter_list|)
block|{
name|String
name|type
init|=
name|metadata
operator|.
name|get
argument_list|(
literal|"my-custom-type-override"
argument_list|)
decl_stmt|;
if|if
condition|(
name|type
operator|!=
literal|null
condition|)
block|{
return|return
name|MediaType
operator|.
name|parse
argument_list|(
name|type
argument_list|)
return|;
block|}
else|else
block|{
return|return
name|MediaType
operator|.
name|OCTET_STREAM
return|;
block|}
block|}
block|}
decl_stmt|;
name|Tika
name|tika
init|=
operator|new
name|Tika
argument_list|(
operator|new
name|CompositeDetector
argument_list|(
name|custom
argument_list|,
name|detector
argument_list|)
argument_list|)
decl_stmt|;
return|return
name|tika
operator|.
name|detect
argument_list|(
name|name
argument_list|)
return|;
block|}
block|}
end_class

end_unit

