begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|parser
operator|.
name|chm
operator|.
name|core
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|parser
operator|.
name|chm
operator|.
name|accessor
operator|.
name|ChmDirectoryListingSet
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|parser
operator|.
name|chm
operator|.
name|accessor
operator|.
name|ChmItsfHeader
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|parser
operator|.
name|chm
operator|.
name|accessor
operator|.
name|ChmItspHeader
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|parser
operator|.
name|chm
operator|.
name|accessor
operator|.
name|ChmLzxcControlData
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|parser
operator|.
name|chm
operator|.
name|accessor
operator|.
name|ChmLzxcResetTable
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|parser
operator|.
name|chm
operator|.
name|lzx
operator|.
name|ChmLzxBlock
import|;
end_import

begin_class
specifier|public
class|class
name|ChmWrapper
block|{
specifier|private
name|List
argument_list|<
name|ChmLzxBlock
argument_list|>
name|lzxBlocksCache
init|=
literal|null
decl_stmt|;
specifier|private
name|ChmDirectoryListingSet
name|chmDirList
init|=
literal|null
decl_stmt|;
specifier|private
name|ChmItsfHeader
name|chmItsfHeader
init|=
literal|null
decl_stmt|;
specifier|private
name|ChmItspHeader
name|chmItspHeader
init|=
literal|null
decl_stmt|;
specifier|private
name|ChmLzxcResetTable
name|chmLzxcResetTable
init|=
literal|null
decl_stmt|;
specifier|private
name|ChmLzxcControlData
name|chmLzxcControlData
init|=
literal|null
decl_stmt|;
specifier|private
name|byte
index|[]
name|data
init|=
literal|null
decl_stmt|;
specifier|private
name|int
name|indexOfContent
decl_stmt|;
specifier|private
name|long
name|lzxBlockOffset
decl_stmt|;
specifier|private
name|long
name|lzxBlockLength
decl_stmt|;
specifier|private
name|int
name|indexOfResetData
decl_stmt|;
specifier|private
name|int
name|indexOfResetTable
decl_stmt|;
specifier|private
name|int
name|startIndex
decl_stmt|;
specifier|protected
name|int
name|getStartIndex
parameter_list|()
block|{
return|return
name|startIndex
return|;
block|}
specifier|protected
name|void
name|setStartIndex
parameter_list|(
name|int
name|startIndex
parameter_list|)
block|{
name|this
operator|.
name|startIndex
operator|=
name|startIndex
expr_stmt|;
block|}
specifier|protected
name|int
name|getIndexOfResetTable
parameter_list|()
block|{
return|return
name|indexOfResetTable
return|;
block|}
specifier|protected
name|void
name|setIndexOfResetTable
parameter_list|(
name|int
name|indexOfResetTable
parameter_list|)
block|{
name|this
operator|.
name|indexOfResetTable
operator|=
name|indexOfResetTable
expr_stmt|;
block|}
specifier|protected
name|List
argument_list|<
name|ChmLzxBlock
argument_list|>
name|getLzxBlocksCache
parameter_list|()
block|{
return|return
name|lzxBlocksCache
return|;
block|}
specifier|protected
name|void
name|setLzxBlocksCache
parameter_list|(
name|List
argument_list|<
name|ChmLzxBlock
argument_list|>
name|lzxBlocksCache
parameter_list|)
block|{
name|this
operator|.
name|lzxBlocksCache
operator|=
name|lzxBlocksCache
expr_stmt|;
block|}
specifier|protected
name|ChmDirectoryListingSet
name|getChmDirList
parameter_list|()
block|{
return|return
name|chmDirList
return|;
block|}
specifier|protected
name|void
name|setChmDirList
parameter_list|(
name|ChmDirectoryListingSet
name|chmDirList
parameter_list|)
block|{
name|this
operator|.
name|chmDirList
operator|=
name|chmDirList
expr_stmt|;
block|}
specifier|protected
name|ChmItsfHeader
name|getChmItsfHeader
parameter_list|()
block|{
return|return
name|chmItsfHeader
return|;
block|}
specifier|protected
name|void
name|setChmItsfHeader
parameter_list|(
name|ChmItsfHeader
name|chmItsfHeader
parameter_list|)
block|{
name|this
operator|.
name|chmItsfHeader
operator|=
name|chmItsfHeader
expr_stmt|;
block|}
specifier|protected
name|ChmLzxcResetTable
name|getChmLzxcResetTable
parameter_list|()
block|{
return|return
name|chmLzxcResetTable
return|;
block|}
specifier|protected
name|void
name|setChmLzxcResetTable
parameter_list|(
name|ChmLzxcResetTable
name|chmLzxcResetTable
parameter_list|)
block|{
name|this
operator|.
name|chmLzxcResetTable
operator|=
name|chmLzxcResetTable
expr_stmt|;
block|}
specifier|protected
name|ChmLzxcControlData
name|getChmLzxcControlData
parameter_list|()
block|{
return|return
name|chmLzxcControlData
return|;
block|}
specifier|protected
name|void
name|setChmLzxcControlData
parameter_list|(
name|ChmLzxcControlData
name|chmLzxcControlData
parameter_list|)
block|{
name|this
operator|.
name|chmLzxcControlData
operator|=
name|chmLzxcControlData
expr_stmt|;
block|}
specifier|protected
name|byte
index|[]
name|getData
parameter_list|()
block|{
return|return
name|data
return|;
block|}
specifier|protected
name|void
name|setData
parameter_list|(
name|byte
index|[]
name|data
parameter_list|)
block|{
name|this
operator|.
name|data
operator|=
name|data
expr_stmt|;
block|}
specifier|protected
name|int
name|getIndexOfContent
parameter_list|()
block|{
return|return
name|indexOfContent
return|;
block|}
specifier|protected
name|void
name|setIndexOfContent
parameter_list|(
name|int
name|indexOfContent
parameter_list|)
block|{
name|this
operator|.
name|indexOfContent
operator|=
name|indexOfContent
expr_stmt|;
block|}
specifier|protected
name|long
name|getLzxBlockOffset
parameter_list|()
block|{
return|return
name|lzxBlockOffset
return|;
block|}
specifier|protected
name|void
name|setLzxBlockOffset
parameter_list|(
name|long
name|lzxBlockOffset
parameter_list|)
block|{
name|this
operator|.
name|lzxBlockOffset
operator|=
name|lzxBlockOffset
expr_stmt|;
block|}
specifier|protected
name|long
name|getLzxBlockLength
parameter_list|()
block|{
return|return
name|lzxBlockLength
return|;
block|}
specifier|protected
name|void
name|setLzxBlockLength
parameter_list|(
name|long
name|lzxBlockLength
parameter_list|)
block|{
name|this
operator|.
name|lzxBlockLength
operator|=
name|lzxBlockLength
expr_stmt|;
block|}
specifier|protected
name|void
name|setChmItspHeader
parameter_list|(
name|ChmItspHeader
name|chmItspHeader
parameter_list|)
block|{
name|this
operator|.
name|chmItspHeader
operator|=
name|chmItspHeader
expr_stmt|;
block|}
specifier|protected
name|ChmItspHeader
name|getChmItspHeader
parameter_list|()
block|{
return|return
name|chmItspHeader
return|;
block|}
specifier|protected
name|void
name|setIndexOfResetData
parameter_list|(
name|int
name|indexOfResetData
parameter_list|)
block|{
name|this
operator|.
name|indexOfResetData
operator|=
name|indexOfResetData
expr_stmt|;
block|}
specifier|protected
name|int
name|getIndexOfResetData
parameter_list|()
block|{
return|return
name|indexOfResetData
return|;
block|}
block|}
end_class

end_unit

