begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|parser
operator|.
name|geo
operator|.
name|topic
operator|.
name|gazetteer
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|Serializable
import|;
end_import

begin_class
specifier|public
class|class
name|Location
implements|implements
name|Serializable
block|{
specifier|private
specifier|static
specifier|final
name|long
name|serialVersionUID
init|=
operator|-
literal|59485448766406004L
decl_stmt|;
specifier|private
name|String
name|name
decl_stmt|;
specifier|private
name|String
name|countryCode
decl_stmt|;
specifier|private
name|String
name|admin1Code
decl_stmt|;
specifier|private
name|String
name|admin2Code
decl_stmt|;
specifier|private
name|String
name|latitude
decl_stmt|;
specifier|private
name|String
name|longitude
decl_stmt|;
specifier|public
name|String
name|getName
parameter_list|()
block|{
return|return
name|name
return|;
block|}
specifier|public
name|void
name|setName
parameter_list|(
name|String
name|name
parameter_list|)
block|{
name|this
operator|.
name|name
operator|=
name|name
expr_stmt|;
block|}
specifier|public
name|String
name|getCountryCode
parameter_list|()
block|{
return|return
name|countryCode
return|;
block|}
specifier|public
name|void
name|setCountryCode
parameter_list|(
name|String
name|countryCode
parameter_list|)
block|{
name|this
operator|.
name|countryCode
operator|=
name|countryCode
expr_stmt|;
block|}
specifier|public
name|String
name|getAdmin1Code
parameter_list|()
block|{
return|return
name|admin1Code
return|;
block|}
specifier|public
name|void
name|setAdmin1Code
parameter_list|(
name|String
name|admin1Code
parameter_list|)
block|{
name|this
operator|.
name|admin1Code
operator|=
name|admin1Code
expr_stmt|;
block|}
specifier|public
name|String
name|getAdmin2Code
parameter_list|()
block|{
return|return
name|admin2Code
return|;
block|}
specifier|public
name|void
name|setAdmin2Code
parameter_list|(
name|String
name|admin2Code
parameter_list|)
block|{
name|this
operator|.
name|admin2Code
operator|=
name|admin2Code
expr_stmt|;
block|}
specifier|public
name|String
name|getLatitude
parameter_list|()
block|{
return|return
name|latitude
return|;
block|}
specifier|public
name|void
name|setLatitude
parameter_list|(
name|String
name|latitude
parameter_list|)
block|{
name|this
operator|.
name|latitude
operator|=
name|latitude
expr_stmt|;
block|}
specifier|public
name|String
name|getLongitude
parameter_list|()
block|{
return|return
name|longitude
return|;
block|}
specifier|public
name|void
name|setLongitude
parameter_list|(
name|String
name|longitude
parameter_list|)
block|{
name|this
operator|.
name|longitude
operator|=
name|longitude
expr_stmt|;
block|}
block|}
end_class

end_unit

