begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|parser
operator|.
name|xml
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|metadata
operator|.
name|DublinCore
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|metadata
operator|.
name|Metadata
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|sax
operator|.
name|TeeContentHandler
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|sax
operator|.
name|xpath
operator|.
name|CompositeMatcher
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|sax
operator|.
name|xpath
operator|.
name|Matcher
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|sax
operator|.
name|xpath
operator|.
name|MatchingContentHandler
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|sax
operator|.
name|xpath
operator|.
name|XPathParser
import|;
end_import

begin_import
import|import
name|org
operator|.
name|xml
operator|.
name|sax
operator|.
name|ContentHandler
import|;
end_import

begin_comment
comment|/**  * Dublin Core metadata parser  */
end_comment

begin_class
specifier|public
class|class
name|DcXMLParser
extends|extends
name|XMLParser
block|{
specifier|private
specifier|static
specifier|final
name|XPathParser
name|DC_XPATH
init|=
operator|new
name|XPathParser
argument_list|(
literal|"dc"
argument_list|,
literal|"http://purl.org/dc/elements/1.1/"
argument_list|)
decl_stmt|;
specifier|private
specifier|static
name|ContentHandler
name|getDublinCore
parameter_list|(
name|ContentHandler
name|ch
parameter_list|,
name|Metadata
name|md
parameter_list|,
name|String
name|name
parameter_list|,
name|String
name|element
parameter_list|)
block|{
name|Matcher
name|matcher
init|=
operator|new
name|CompositeMatcher
argument_list|(
name|DC_XPATH
operator|.
name|parse
argument_list|(
literal|"//dc:"
operator|+
name|element
argument_list|)
argument_list|,
name|DC_XPATH
operator|.
name|parse
argument_list|(
literal|"//dc:"
operator|+
name|element
operator|+
literal|"//text()"
argument_list|)
argument_list|)
decl_stmt|;
name|ContentHandler
name|branch
init|=
operator|new
name|MatchingContentHandler
argument_list|(
operator|new
name|MetadataHandler
argument_list|(
name|md
argument_list|,
name|name
argument_list|)
argument_list|,
name|matcher
argument_list|)
decl_stmt|;
return|return
operator|new
name|TeeContentHandler
argument_list|(
name|ch
argument_list|,
name|branch
argument_list|)
return|;
block|}
specifier|protected
name|ContentHandler
name|getContentHandler
parameter_list|(
name|ContentHandler
name|ch
parameter_list|,
name|Metadata
name|md
parameter_list|)
block|{
name|ch
operator|=
name|super
operator|.
name|getContentHandler
argument_list|(
name|ch
argument_list|,
name|md
argument_list|)
expr_stmt|;
name|ch
operator|=
name|getDublinCore
argument_list|(
name|ch
argument_list|,
name|md
argument_list|,
name|DublinCore
operator|.
name|TITLE
argument_list|,
literal|"title"
argument_list|)
expr_stmt|;
name|ch
operator|=
name|getDublinCore
argument_list|(
name|ch
argument_list|,
name|md
argument_list|,
name|DublinCore
operator|.
name|SUBJECT
argument_list|,
literal|"subject"
argument_list|)
expr_stmt|;
name|ch
operator|=
name|getDublinCore
argument_list|(
name|ch
argument_list|,
name|md
argument_list|,
name|DublinCore
operator|.
name|CREATOR
argument_list|,
literal|"creator"
argument_list|)
expr_stmt|;
name|ch
operator|=
name|getDublinCore
argument_list|(
name|ch
argument_list|,
name|md
argument_list|,
name|DublinCore
operator|.
name|DESCRIPTION
argument_list|,
literal|"description"
argument_list|)
expr_stmt|;
name|ch
operator|=
name|getDublinCore
argument_list|(
name|ch
argument_list|,
name|md
argument_list|,
name|DublinCore
operator|.
name|PUBLISHER
argument_list|,
literal|"publisher"
argument_list|)
expr_stmt|;
name|ch
operator|=
name|getDublinCore
argument_list|(
name|ch
argument_list|,
name|md
argument_list|,
name|DublinCore
operator|.
name|CONTRIBUTOR
argument_list|,
literal|"contributor"
argument_list|)
expr_stmt|;
try|try
block|{
name|ch
operator|=
name|getDublinCore
argument_list|(
name|ch
argument_list|,
name|md
argument_list|,
name|DublinCore
operator|.
name|DATE
operator|.
name|getName
argument_list|()
argument_list|,
literal|"date"
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|Exception
name|e
parameter_list|)
block|{
comment|// Date format and parsing behavior was undefined and untested when DublinCare
comment|// date was converted to Property.internalDate so we silently skip date on parse error
block|}
name|ch
operator|=
name|getDublinCore
argument_list|(
name|ch
argument_list|,
name|md
argument_list|,
name|DublinCore
operator|.
name|TYPE
argument_list|,
literal|"type"
argument_list|)
expr_stmt|;
name|ch
operator|=
name|getDublinCore
argument_list|(
name|ch
argument_list|,
name|md
argument_list|,
name|DublinCore
operator|.
name|FORMAT
argument_list|,
literal|"format"
argument_list|)
expr_stmt|;
name|ch
operator|=
name|getDublinCore
argument_list|(
name|ch
argument_list|,
name|md
argument_list|,
name|DublinCore
operator|.
name|IDENTIFIER
argument_list|,
literal|"identifier"
argument_list|)
expr_stmt|;
name|ch
operator|=
name|getDublinCore
argument_list|(
name|ch
argument_list|,
name|md
argument_list|,
name|DublinCore
operator|.
name|LANGUAGE
argument_list|,
literal|"language"
argument_list|)
expr_stmt|;
name|ch
operator|=
name|getDublinCore
argument_list|(
name|ch
argument_list|,
name|md
argument_list|,
name|DublinCore
operator|.
name|RIGHTS
argument_list|,
literal|"rights"
argument_list|)
expr_stmt|;
return|return
name|ch
return|;
block|}
block|}
end_class

end_unit

