begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|batch
operator|.
name|fs
package|;
end_package

begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|nio
operator|.
name|file
operator|.
name|DirectoryStream
import|;
end_import

begin_import
import|import
name|java
operator|.
name|nio
operator|.
name|file
operator|.
name|Files
import|;
end_import

begin_import
import|import
name|java
operator|.
name|nio
operator|.
name|file
operator|.
name|Path
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|ArrayList
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Collections
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Comparator
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|LinkedList
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|concurrent
operator|.
name|ArrayBlockingQueue
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|batch
operator|.
name|FileResource
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|batch
operator|.
name|FileResourceCrawler
import|;
end_import

begin_class
specifier|public
class|class
name|FSDirectoryCrawler
extends|extends
name|FileResourceCrawler
block|{
specifier|public
enum|enum
name|CRAWL_ORDER
block|{
name|SORTED
block|,
comment|//alphabetical order; necessary for cross-platform unit tests
name|RANDOM
block|,
comment|//shuffle
name|OS_ORDER
comment|//operating system chooses
block|}
specifier|private
specifier|final
name|Path
name|root
decl_stmt|;
specifier|private
specifier|final
name|Path
name|startDirectory
decl_stmt|;
specifier|private
specifier|final
name|Comparator
argument_list|<
name|Path
argument_list|>
name|pathComparator
init|=
operator|new
name|FileNameComparator
argument_list|()
decl_stmt|;
specifier|private
name|CRAWL_ORDER
name|crawlOrder
decl_stmt|;
specifier|public
name|FSDirectoryCrawler
parameter_list|(
name|ArrayBlockingQueue
argument_list|<
name|FileResource
argument_list|>
name|fileQueue
parameter_list|,
name|int
name|numConsumers
parameter_list|,
name|Path
name|root
parameter_list|,
name|CRAWL_ORDER
name|crawlOrder
parameter_list|)
block|{
name|super
argument_list|(
name|fileQueue
argument_list|,
name|numConsumers
argument_list|)
expr_stmt|;
name|this
operator|.
name|root
operator|=
name|root
expr_stmt|;
name|this
operator|.
name|startDirectory
operator|=
name|root
expr_stmt|;
name|this
operator|.
name|crawlOrder
operator|=
name|crawlOrder
expr_stmt|;
if|if
condition|(
operator|!
name|Files
operator|.
name|isDirectory
argument_list|(
name|startDirectory
argument_list|)
condition|)
block|{
throw|throw
operator|new
name|RuntimeException
argument_list|(
literal|"Crawler couldn't find this directory:"
operator|+
name|startDirectory
operator|.
name|toAbsolutePath
argument_list|()
argument_list|)
throw|;
block|}
block|}
specifier|public
name|FSDirectoryCrawler
parameter_list|(
name|ArrayBlockingQueue
argument_list|<
name|FileResource
argument_list|>
name|fileQueue
parameter_list|,
name|int
name|numConsumers
parameter_list|,
name|Path
name|root
parameter_list|,
name|Path
name|startDirectory
parameter_list|,
name|CRAWL_ORDER
name|crawlOrder
parameter_list|)
block|{
name|super
argument_list|(
name|fileQueue
argument_list|,
name|numConsumers
argument_list|)
expr_stmt|;
name|this
operator|.
name|root
operator|=
name|root
expr_stmt|;
name|this
operator|.
name|startDirectory
operator|=
name|startDirectory
expr_stmt|;
name|this
operator|.
name|crawlOrder
operator|=
name|crawlOrder
expr_stmt|;
assert|assert
operator|(
name|startDirectory
operator|.
name|toAbsolutePath
argument_list|()
operator|.
name|startsWith
argument_list|(
name|root
operator|.
name|toAbsolutePath
argument_list|()
argument_list|)
operator|)
assert|;
if|if
condition|(
operator|!
name|Files
operator|.
name|isDirectory
argument_list|(
name|startDirectory
argument_list|)
condition|)
block|{
throw|throw
operator|new
name|RuntimeException
argument_list|(
literal|"Crawler couldn't find this directory:"
operator|+
name|startDirectory
operator|.
name|toAbsolutePath
argument_list|()
argument_list|)
throw|;
block|}
block|}
specifier|public
name|void
name|start
parameter_list|()
throws|throws
name|InterruptedException
block|{
name|addFiles
argument_list|(
name|startDirectory
argument_list|)
expr_stmt|;
block|}
specifier|private
name|void
name|addFiles
parameter_list|(
name|Path
name|directory
parameter_list|)
throws|throws
name|InterruptedException
block|{
if|if
condition|(
name|directory
operator|==
literal|null
condition|)
block|{
name|LOG
operator|.
name|warn
argument_list|(
literal|"FSFileAdder asked to process null directory?!"
argument_list|)
expr_stmt|;
return|return;
block|}
name|List
argument_list|<
name|Path
argument_list|>
name|files
init|=
operator|new
name|ArrayList
argument_list|<>
argument_list|()
decl_stmt|;
try|try
init|(
name|DirectoryStream
argument_list|<
name|Path
argument_list|>
name|ds
init|=
name|Files
operator|.
name|newDirectoryStream
argument_list|(
name|directory
argument_list|)
init|)
block|{
for|for
control|(
name|Path
name|p
range|:
name|ds
control|)
block|{
name|files
operator|.
name|add
argument_list|(
name|p
argument_list|)
expr_stmt|;
block|}
block|}
catch|catch
parameter_list|(
name|IOException
name|e
parameter_list|)
block|{
name|LOG
operator|.
name|warn
argument_list|(
literal|"FSFileAdder couldn't read {}: {}"
argument_list|,
name|directory
operator|.
name|toAbsolutePath
argument_list|()
argument_list|,
name|e
operator|.
name|getMessage
argument_list|()
argument_list|,
name|e
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|files
operator|.
name|size
argument_list|()
operator|==
literal|0
condition|)
block|{
name|LOG
operator|.
name|info
argument_list|(
literal|"Empty directory: {}"
argument_list|,
name|directory
operator|.
name|toAbsolutePath
argument_list|()
argument_list|)
expr_stmt|;
return|return;
block|}
if|if
condition|(
name|crawlOrder
operator|==
name|CRAWL_ORDER
operator|.
name|RANDOM
condition|)
block|{
name|Collections
operator|.
name|shuffle
argument_list|(
name|files
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|crawlOrder
operator|==
name|CRAWL_ORDER
operator|.
name|SORTED
condition|)
block|{
name|Collections
operator|.
name|sort
argument_list|(
name|files
argument_list|,
name|pathComparator
argument_list|)
expr_stmt|;
block|}
name|int
name|numFiles
init|=
literal|0
decl_stmt|;
name|List
argument_list|<
name|Path
argument_list|>
name|directories
init|=
operator|new
name|LinkedList
argument_list|<>
argument_list|()
decl_stmt|;
for|for
control|(
name|Path
name|f
range|:
name|files
control|)
block|{
if|if
condition|(
name|Thread
operator|.
name|currentThread
argument_list|()
operator|.
name|isInterrupted
argument_list|()
condition|)
block|{
throw|throw
operator|new
name|InterruptedException
argument_list|(
literal|"file adder interrupted"
argument_list|)
throw|;
block|}
if|if
condition|(
operator|!
name|Files
operator|.
name|isReadable
argument_list|(
name|f
argument_list|)
condition|)
block|{
name|LOG
operator|.
name|warn
argument_list|(
literal|"Skipping -- {} -- file/directory is not readable"
argument_list|,
name|f
operator|.
name|toAbsolutePath
argument_list|()
argument_list|)
expr_stmt|;
continue|continue;
block|}
if|if
condition|(
name|Files
operator|.
name|isDirectory
argument_list|(
name|f
argument_list|)
condition|)
block|{
name|directories
operator|.
name|add
argument_list|(
name|f
argument_list|)
expr_stmt|;
continue|continue;
block|}
name|numFiles
operator|++
expr_stmt|;
if|if
condition|(
name|numFiles
operator|==
literal|1
condition|)
block|{
name|handleFirstFileInDirectory
argument_list|(
name|f
argument_list|)
expr_stmt|;
block|}
name|int
name|added
init|=
name|tryToAdd
argument_list|(
operator|new
name|FSFileResource
argument_list|(
name|root
argument_list|,
name|f
argument_list|)
argument_list|)
decl_stmt|;
if|if
condition|(
name|added
operator|==
name|FileResourceCrawler
operator|.
name|STOP_NOW
condition|)
block|{
name|LOG
operator|.
name|debug
argument_list|(
literal|"crawler has hit a limit: {} : {}"
argument_list|,
name|f
operator|.
name|toAbsolutePath
argument_list|()
argument_list|,
name|added
argument_list|)
expr_stmt|;
return|return;
block|}
name|LOG
operator|.
name|debug
argument_list|(
literal|"trying to add: {} : {}"
argument_list|,
name|f
operator|.
name|toAbsolutePath
argument_list|()
argument_list|,
name|added
argument_list|)
expr_stmt|;
block|}
for|for
control|(
name|Path
name|f
range|:
name|directories
control|)
block|{
name|addFiles
argument_list|(
name|f
argument_list|)
expr_stmt|;
block|}
block|}
comment|/**      * Override this if you have any special handling      * for the first actual file that the crawler comes across      * in a directory.  For example, it might be handy to call      * mkdirs() on an output directory if your FileResourceConsumers      * are writing to a file.      *      * @param f file to handle      */
specifier|public
name|void
name|handleFirstFileInDirectory
parameter_list|(
name|Path
name|f
parameter_list|)
block|{
comment|//no-op
block|}
comment|//simple lexical order for the file name, we don't really care about localization.
comment|//we do want this, though, because file.compareTo behaves differently
comment|//on different OS's.
specifier|private
class|class
name|FileNameComparator
implements|implements
name|Comparator
argument_list|<
name|Path
argument_list|>
block|{
annotation|@
name|Override
specifier|public
name|int
name|compare
parameter_list|(
name|Path
name|f1
parameter_list|,
name|Path
name|f2
parameter_list|)
block|{
if|if
condition|(
name|f1
operator|==
literal|null
operator|||
name|f2
operator|==
literal|null
condition|)
block|{
return|return
literal|0
return|;
block|}
return|return
name|f1
operator|.
name|getFileName
argument_list|()
operator|.
name|toString
argument_list|()
operator|.
name|compareTo
argument_list|(
name|f2
operator|.
name|getFileName
argument_list|()
operator|.
name|toString
argument_list|()
argument_list|)
return|;
block|}
block|}
block|}
end_class

end_unit

