begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|example
package|;
end_package

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Before
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Test
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Locale
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|junit
operator|.
name|Assert
operator|.
name|assertEquals
import|;
end_import

begin_class
specifier|public
class|class
name|TranslatorExampleTest
block|{
name|TranslatorExample
name|translatorExample
decl_stmt|;
annotation|@
name|Before
specifier|public
name|void
name|setUp
parameter_list|()
block|{
name|translatorExample
operator|=
operator|new
name|TranslatorExample
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testMicrosoftTranslateToFrench
parameter_list|()
block|{
name|String
name|text
init|=
literal|"hello"
decl_stmt|;
name|String
name|expected
init|=
literal|"salut"
decl_stmt|;
name|String
name|translated
init|=
name|translatorExample
operator|.
name|microsoftTranslateToFrench
argument_list|(
name|text
argument_list|)
decl_stmt|;
comment|// The user may not have set the id and secret. So, we have to check if we just
comment|// got the same text back.
if|if
condition|(
operator|!
name|translated
operator|.
name|equals
argument_list|(
name|text
argument_list|)
condition|)
name|assertEquals
argument_list|(
name|expected
argument_list|,
name|translated
operator|.
name|toLowerCase
argument_list|(
name|Locale
operator|.
name|ROOT
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

