begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|mime
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|junit
operator|.
name|framework
operator|.
name|TestCase
import|;
end_import

begin_class
specifier|public
class|class
name|PatternsTest
extends|extends
name|TestCase
block|{
specifier|private
name|MimeTypes
name|types
init|=
name|MimeTypes
operator|.
name|getDefaultMimeTypes
argument_list|()
decl_stmt|;
specifier|public
name|void
name|testExtensions
parameter_list|()
throws|throws
name|Exception
block|{
name|MimeType
name|jpeg
init|=
name|types
operator|.
name|forName
argument_list|(
literal|"image/jpeg"
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
literal|".jpg"
argument_list|,
name|jpeg
operator|.
name|getExtension
argument_list|()
argument_list|)
expr_stmt|;
name|List
argument_list|<
name|String
argument_list|>
name|extensions
init|=
name|jpeg
operator|.
name|getExtensions
argument_list|()
decl_stmt|;
name|assertTrue
argument_list|(
name|extensions
operator|.
name|size
argument_list|()
operator|>
literal|1
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|extensions
operator|.
name|contains
argument_list|(
literal|".jpg"
argument_list|)
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|extensions
operator|.
name|contains
argument_list|(
literal|".jpeg"
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

