begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|parser
operator|.
name|microsoft
operator|.
name|ooxml
package|;
end_package

begin_comment
comment|/**  * WARNING: This class is mutable.  Make a copy of it  * if you want persistence!  */
end_comment

begin_class
specifier|public
class|class
name|RunProperties
block|{
name|boolean
name|italics
init|=
literal|false
decl_stmt|;
name|boolean
name|bold
init|=
literal|false
decl_stmt|;
specifier|public
name|boolean
name|getItalics
parameter_list|()
block|{
return|return
name|italics
return|;
block|}
specifier|public
name|boolean
name|getBold
parameter_list|()
block|{
return|return
name|bold
return|;
block|}
specifier|public
name|void
name|setItalics
parameter_list|(
name|boolean
name|italics
parameter_list|)
block|{
name|this
operator|.
name|italics
operator|=
name|italics
expr_stmt|;
block|}
specifier|public
name|void
name|setBold
parameter_list|(
name|boolean
name|bold
parameter_list|)
block|{
name|this
operator|.
name|bold
operator|=
name|bold
expr_stmt|;
block|}
block|}
end_class

end_unit

