begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|metadata
package|;
end_package

begin_comment
comment|/**  * A collection of Message related property names.  *  * See also {@link Office}'s MAPI-specific properties.  */
end_comment

begin_interface
specifier|public
interface|interface
name|Message
block|{
name|String
name|MESSAGE_PREFIX
init|=
literal|"Message"
operator|+
name|Metadata
operator|.
name|NAMESPACE_PREFIX_DELIMITER
decl_stmt|;
name|String
name|MESSAGE_RAW_HEADER_PREFIX
init|=
name|MESSAGE_PREFIX
operator|+
literal|"Raw-Header"
operator|+
name|Metadata
operator|.
name|NAMESPACE_PREFIX_DELIMITER
decl_stmt|;
name|String
name|MESSAGE_RECIPIENT_ADDRESS
init|=
literal|"Message-Recipient-Address"
decl_stmt|;
name|String
name|MESSAGE_FROM
init|=
literal|"Message-From"
decl_stmt|;
name|String
name|MESSAGE_TO
init|=
literal|"Message-To"
decl_stmt|;
name|String
name|MESSAGE_CC
init|=
literal|"Message-Cc"
decl_stmt|;
name|String
name|MESSAGE_BCC
init|=
literal|"Message-Bcc"
decl_stmt|;
comment|/**      * Where possible, this records the value from the name field.      * Even in MAPI messages, though, this can be an email address.      */
name|Property
name|MESSAGE_FROM_NAME
init|=
name|Property
operator|.
name|internalTextBag
argument_list|(
name|MESSAGE_PREFIX
operator|+
literal|"From-Name"
argument_list|)
decl_stmt|;
comment|/**      * Where possible, this records the value from the name field.      * Even in MAPI messages, though, this can be a name.      *<p/>      * Note that the value may also be an X400/x500 Exchange format:      * /o=ExchangeLabs/ou=Exchange Administrative Group/cn=Recipients/cn=someone.or.other      */
name|Property
name|MESSAGE_FROM_EMAIL
init|=
name|Property
operator|.
name|internalTextBag
argument_list|(
name|MESSAGE_PREFIX
operator|+
literal|"From-Email"
argument_list|)
decl_stmt|;
comment|/**      * In Outlook messages, there are sometimes separate fields for "to-name" and      * "to-display-name" name.      */
name|Property
name|MESSAGE_TO_NAME
init|=
name|Property
operator|.
name|internalTextBag
argument_list|(
name|MESSAGE_PREFIX
operator|+
literal|"To-Name"
argument_list|)
decl_stmt|;
name|Property
name|MESSAGE_TO_DISPLAY_NAME
init|=
name|Property
operator|.
name|internalTextBag
argument_list|(
name|MESSAGE_PREFIX
operator|+
literal|"To-Display-Name"
argument_list|)
decl_stmt|;
comment|/**      * Where possible, this records the email value in the to field.      * Even in MAPI messages, though, this can be a name.      *<p/>      * Note that the value may also be an X400/x500 Exchange format:      * /o=ExchangeLabs/ou=Exchange Administrative Group/cn=Recipients/cn=someone.or.other      */
name|Property
name|MESSAGE_TO_EMAIL
init|=
name|Property
operator|.
name|internalTextBag
argument_list|(
name|MESSAGE_PREFIX
operator|+
literal|"To-Email"
argument_list|)
decl_stmt|;
comment|/**      * In Outlook messages, there are sometimes separate fields for "cc-name" and      * "cc-display-name" name.      */
name|Property
name|MESSAGE_CC_NAME
init|=
name|Property
operator|.
name|internalTextBag
argument_list|(
name|MESSAGE_PREFIX
operator|+
literal|"CC-Name"
argument_list|)
decl_stmt|;
name|Property
name|MESSAGE_CC_DISPLAY_NAME
init|=
name|Property
operator|.
name|internalTextBag
argument_list|(
name|MESSAGE_PREFIX
operator|+
literal|"CC-Display-Name"
argument_list|)
decl_stmt|;
comment|/**      * Where possible, this records the email value in the cc field.      * Even in MAPI messages, though, this can be a name.      *<p/>      * Note that the value may also be an X400/x500 Exchange format:      * /o=ExchangeLabs/ou=Exchange Administrative Group/cn=Recipients/cn=someone.or.other      */
name|Property
name|MESSAGE_CC_EMAIL
init|=
name|Property
operator|.
name|internalTextBag
argument_list|(
name|MESSAGE_PREFIX
operator|+
literal|"CC-Email"
argument_list|)
decl_stmt|;
comment|/**      * In Outlook messages, there are sometimes separate fields for "bcc-name" and      * "bcc-display-name" name.      */
name|Property
name|MESSAGE_BCC_NAME
init|=
name|Property
operator|.
name|internalTextBag
argument_list|(
name|MESSAGE_PREFIX
operator|+
literal|"BCC-Name"
argument_list|)
decl_stmt|;
name|Property
name|MESSAGE_BCC_DISPLAY_NAME
init|=
name|Property
operator|.
name|internalTextBag
argument_list|(
name|MESSAGE_PREFIX
operator|+
literal|"BCC-Display-Name"
argument_list|)
decl_stmt|;
comment|/**      * Where possible, this records the email value in the bcc field.      * Even in MAPI messages, though, this can be a name.      *<p/>      * Note that the value may also be an X400/x500 Exchange format:      * /o=ExchangeLabs/ou=Exchange Administrative Group/cn=Recipients/cn=someone.or.other      */
name|Property
name|MESSAGE_BCC_EMAIL
init|=
name|Property
operator|.
name|internalTextBag
argument_list|(
name|MESSAGE_PREFIX
operator|+
literal|"BCC-Email"
argument_list|)
decl_stmt|;
block|}
end_interface

end_unit

