begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|parser
operator|.
name|microsoft
operator|.
name|onenote
package|;
end_package

begin_class
class|class
name|RevisionManifest
block|{
name|ExtendedGUID
name|ridDependent
decl_stmt|;
name|long
name|timeCreation
decl_stmt|;
comment|//ignored
name|long
name|revisionRole
decl_stmt|;
name|long
name|odcsDefault
decl_stmt|;
specifier|public
name|ExtendedGUID
name|getRidDependent
parameter_list|()
block|{
return|return
name|ridDependent
return|;
block|}
specifier|public
name|RevisionManifest
name|setRidDependent
parameter_list|(
name|ExtendedGUID
name|ridDependent
parameter_list|)
block|{
name|this
operator|.
name|ridDependent
operator|=
name|ridDependent
expr_stmt|;
return|return
name|this
return|;
block|}
specifier|public
name|long
name|getTimeCreation
parameter_list|()
block|{
return|return
name|timeCreation
return|;
block|}
specifier|public
name|RevisionManifest
name|setTimeCreation
parameter_list|(
name|long
name|timeCreation
parameter_list|)
block|{
name|this
operator|.
name|timeCreation
operator|=
name|timeCreation
expr_stmt|;
return|return
name|this
return|;
block|}
specifier|public
name|long
name|getRevisionRole
parameter_list|()
block|{
return|return
name|revisionRole
return|;
block|}
specifier|public
name|RevisionManifest
name|setRevisionRole
parameter_list|(
name|long
name|revisionRole
parameter_list|)
block|{
name|this
operator|.
name|revisionRole
operator|=
name|revisionRole
expr_stmt|;
return|return
name|this
return|;
block|}
specifier|public
name|long
name|getOdcsDefault
parameter_list|()
block|{
return|return
name|odcsDefault
return|;
block|}
specifier|public
name|RevisionManifest
name|setOdcsDefault
parameter_list|(
name|long
name|odcsDefault
parameter_list|)
block|{
name|this
operator|.
name|odcsDefault
operator|=
name|odcsDefault
expr_stmt|;
return|return
name|this
return|;
block|}
block|}
end_class

end_unit

