name: tika-app # you probably want to 'snapcraft register <name>'
version: '1.16' # just for humans, typically '1.2+git' or '1.3.2'
summary: Tika Server for metadata discovery and extraction # 79 char long summary
description: Apache Tika is a content detection and analysis framework, written 
      in Java, stewarded at the Apache Software Foundation.It detects and extracts 
      metadata and text from over a thousand different file types, and as well as 
      providing a Java library, has server and command-line editions suitable for 
      use from other programming languages.
   
grade: stable
confinement: strict

apps:
   run:
    command: java -jar  -Duser.home=$SNAP_USER_DATA $SNAP/jar/tika-app-1.16-SNAPSHOT.jar
    plugs: [home, removable-media]
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-8-openjdk-amd64
      PATH: $JAVA_HOME/jre/bin:$PATH
      XDG_DATA_HOME: $SNAP/usr/share
      FONTCONFIG_PATH: $SNAP/etc/fonts/config.d
      FONTCONFIG_FILE: $SNAP/etc/fonts/fonts.conf

parts:
  compile-tika:
    source: ../tika-app
    plugin: maven
    maven-options: [-DskipTests]