begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|parser
operator|.
name|pdf
package|;
end_package

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|stream
operator|.
name|XMLStreamException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|ByteArrayInputStream
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|InputStream
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Arrays
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Calendar
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Collections
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Locale
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Map
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Set
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|commons
operator|.
name|io
operator|.
name|input
operator|.
name|CloseShieldInputStream
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|cos
operator|.
name|COSDictionary
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|cos
operator|.
name|COSName
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|io
operator|.
name|MemoryUsageSetting
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|PDDocument
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|PDDocumentInformation
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|encryption
operator|.
name|AccessPermission
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|encryption
operator|.
name|InvalidPasswordException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|config
operator|.
name|Field
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|config
operator|.
name|Initializable
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|config
operator|.
name|InitializableProblemHandler
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|config
operator|.
name|Param
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|exception
operator|.
name|EncryptedDocumentException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|exception
operator|.
name|TikaConfigException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|exception
operator|.
name|TikaException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|extractor
operator|.
name|EmbeddedDocumentExtractor
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|io
operator|.
name|TikaInputStream
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|metadata
operator|.
name|AccessPermissions
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|metadata
operator|.
name|Metadata
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|metadata
operator|.
name|Office
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|metadata
operator|.
name|OfficeOpenXMLCore
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|metadata
operator|.
name|PDF
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|metadata
operator|.
name|PagedText
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|metadata
operator|.
name|TikaCoreProperties
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|mime
operator|.
name|MediaType
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|parser
operator|.
name|AbstractParser
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|parser
operator|.
name|ParseContext
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|parser
operator|.
name|PasswordProvider
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|parser
operator|.
name|ocr
operator|.
name|TesseractOCRParser
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|sax
operator|.
name|XHTMLContentHandler
import|;
end_import

begin_import
import|import
name|org
operator|.
name|xml
operator|.
name|sax
operator|.
name|ContentHandler
import|;
end_import

begin_import
import|import
name|org
operator|.
name|xml
operator|.
name|sax
operator|.
name|SAXException
import|;
end_import

begin_comment
comment|/**  * PDF parser.  *<p/>  * This parser can process also encrypted PDF documents if the required  * password is given as a part of the input metadata associated with a  * document. If no password is given, then this parser will try decrypting  * the document using the empty password that's often used with PDFs. If  * the PDF contains any embedded documents (for example as part of a PDF  * package) then this parser will use the {@link EmbeddedDocumentExtractor}  * to handle them.  *<p/>  * As of Tika 1.6, it is possible to extract inline images with  * the {@link EmbeddedDocumentExtractor} as if they were regular  * attachments.  By default, this feature is turned off because of  * the potentially enormous number and size of inline images.  To  * turn this feature on, see  * {@link PDFParserConfig#setExtractInlineImages(boolean)}.  *<p/>  * Please note that tables are not stored as entities within PDFs. It  * takes significant computation to identify and then correctly extract  * tables from PDFs. As of this writing, the {@link PDFParser} extracts  * text within tables, but it does not compute table cell boundaries or  * table row boundaries. Please see  *<a href="http://tabula.technology/">tabula</a> for one project that  * tries to maintain the structure of tables represented in PDFs.  */
end_comment

begin_class
specifier|public
class|class
name|PDFParser
extends|extends
name|AbstractParser
implements|implements
name|Initializable
block|{
specifier|private
specifier|static
specifier|volatile
name|boolean
name|HAS_WARNED
init|=
literal|false
decl_stmt|;
specifier|private
specifier|static
specifier|final
name|Object
index|[]
name|LOCK
init|=
operator|new
name|Object
index|[
literal|0
index|]
decl_stmt|;
comment|/**      * Metadata key for giving the document password to the parser.      *      * @since Apache Tika 0.5      * @deprecated Supply a {@link PasswordProvider} on the {@link ParseContext} instead      */
specifier|public
specifier|static
specifier|final
name|String
name|PASSWORD
init|=
literal|"org.apache.tika.parser.pdf.password"
decl_stmt|;
specifier|private
specifier|static
specifier|final
name|MediaType
name|MEDIA_TYPE
init|=
name|MediaType
operator|.
name|application
argument_list|(
literal|"pdf"
argument_list|)
decl_stmt|;
comment|/**      * Serial version UID      */
specifier|private
specifier|static
specifier|final
name|long
name|serialVersionUID
init|=
operator|-
literal|752276948656079347L
decl_stmt|;
specifier|private
specifier|static
specifier|final
name|Set
argument_list|<
name|MediaType
argument_list|>
name|SUPPORTED_TYPES
init|=
name|Collections
operator|.
name|singleton
argument_list|(
name|MEDIA_TYPE
argument_list|)
decl_stmt|;
specifier|private
name|PDFParserConfig
name|defaultConfig
init|=
operator|new
name|PDFParserConfig
argument_list|()
decl_stmt|;
specifier|private
name|InitializableProblemHandler
name|initializableProblemHandler
init|=
literal|null
decl_stmt|;
specifier|public
name|Set
argument_list|<
name|MediaType
argument_list|>
name|getSupportedTypes
parameter_list|(
name|ParseContext
name|context
parameter_list|)
block|{
return|return
name|SUPPORTED_TYPES
return|;
block|}
specifier|public
name|void
name|parse
parameter_list|(
name|InputStream
name|stream
parameter_list|,
name|ContentHandler
name|handler
parameter_list|,
name|Metadata
name|metadata
parameter_list|,
name|ParseContext
name|context
parameter_list|)
throws|throws
name|IOException
throws|,
name|SAXException
throws|,
name|TikaException
block|{
name|PDFParserConfig
name|localConfig
init|=
name|context
operator|.
name|get
argument_list|(
name|PDFParserConfig
operator|.
name|class
argument_list|,
name|defaultConfig
argument_list|)
decl_stmt|;
if|if
condition|(
name|localConfig
operator|.
name|getSetKCMS
argument_list|()
condition|)
block|{
name|System
operator|.
name|setProperty
argument_list|(
literal|"sun.java2d.cmm"
argument_list|,
literal|"sun.java2d.cmm.kcms.KcmsServiceProvider"
argument_list|)
expr_stmt|;
block|}
name|PDDocument
name|pdfDocument
init|=
literal|null
decl_stmt|;
name|String
name|password
init|=
literal|""
decl_stmt|;
try|try
block|{
name|TikaInputStream
name|tstream
init|=
name|TikaInputStream
operator|.
name|cast
argument_list|(
name|stream
argument_list|)
decl_stmt|;
name|password
operator|=
name|getPassword
argument_list|(
name|metadata
argument_list|,
name|context
argument_list|)
expr_stmt|;
name|MemoryUsageSetting
name|memoryUsageSetting
init|=
name|MemoryUsageSetting
operator|.
name|setupMainMemoryOnly
argument_list|()
decl_stmt|;
if|if
condition|(
name|localConfig
operator|.
name|getMaxMainMemoryBytes
argument_list|()
operator|>=
literal|0
condition|)
block|{
name|memoryUsageSetting
operator|=
name|MemoryUsageSetting
operator|.
name|setupMixed
argument_list|(
name|localConfig
operator|.
name|getMaxMainMemoryBytes
argument_list|()
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|tstream
operator|!=
literal|null
operator|&&
name|tstream
operator|.
name|hasFile
argument_list|()
condition|)
block|{
comment|// File based -- send file directly to PDFBox
name|pdfDocument
operator|=
name|PDDocument
operator|.
name|load
argument_list|(
name|tstream
operator|.
name|getPath
argument_list|()
operator|.
name|toFile
argument_list|()
argument_list|,
name|password
argument_list|,
name|memoryUsageSetting
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|pdfDocument
operator|=
name|PDDocument
operator|.
name|load
argument_list|(
operator|new
name|CloseShieldInputStream
argument_list|(
name|stream
argument_list|)
argument_list|,
name|password
argument_list|,
name|memoryUsageSetting
argument_list|)
expr_stmt|;
block|}
name|metadata
operator|.
name|set
argument_list|(
name|PDF
operator|.
name|IS_ENCRYPTED
argument_list|,
name|Boolean
operator|.
name|toString
argument_list|(
name|pdfDocument
operator|.
name|isEncrypted
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|metadata
operator|.
name|set
argument_list|(
name|Metadata
operator|.
name|CONTENT_TYPE
argument_list|,
name|MEDIA_TYPE
operator|.
name|toString
argument_list|()
argument_list|)
expr_stmt|;
name|extractMetadata
argument_list|(
name|pdfDocument
argument_list|,
name|metadata
argument_list|,
name|context
argument_list|)
expr_stmt|;
name|AccessChecker
name|checker
init|=
name|localConfig
operator|.
name|getAccessChecker
argument_list|()
decl_stmt|;
name|checker
operator|.
name|check
argument_list|(
name|metadata
argument_list|)
expr_stmt|;
if|if
condition|(
name|handler
operator|!=
literal|null
condition|)
block|{
name|boolean
name|hasXFA
init|=
name|hasXFA
argument_list|(
name|pdfDocument
argument_list|)
decl_stmt|;
name|metadata
operator|.
name|set
argument_list|(
name|PDF
operator|.
name|HAS_XFA
argument_list|,
name|Boolean
operator|.
name|toString
argument_list|(
name|hasXFA
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|shouldHandleXFAOnly
argument_list|(
name|hasXFA
argument_list|,
name|localConfig
argument_list|)
condition|)
block|{
name|handleXFAOnly
argument_list|(
name|pdfDocument
argument_list|,
name|handler
argument_list|,
name|metadata
argument_list|,
name|context
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|localConfig
operator|.
name|getOcrStrategy
argument_list|()
operator|.
name|equals
argument_list|(
name|PDFParserConfig
operator|.
name|OCR_STRATEGY
operator|.
name|OCR_ONLY
argument_list|)
condition|)
block|{
name|metadata
operator|.
name|add
argument_list|(
literal|"X-Parsed-By"
argument_list|,
name|TesseractOCRParser
operator|.
name|class
operator|.
name|toString
argument_list|()
argument_list|)
expr_stmt|;
name|OCR2XHTML
operator|.
name|process
argument_list|(
name|pdfDocument
argument_list|,
name|handler
argument_list|,
name|context
argument_list|,
name|metadata
argument_list|,
name|localConfig
argument_list|)
expr_stmt|;
block|}
else|else
block|{
if|if
condition|(
name|localConfig
operator|.
name|getOcrStrategy
argument_list|()
operator|.
name|equals
argument_list|(
name|PDFParserConfig
operator|.
name|OCR_STRATEGY
operator|.
name|OCR_AND_TEXT_EXTRACTION
argument_list|)
condition|)
block|{
name|metadata
operator|.
name|add
argument_list|(
literal|"X-Parsed-By"
argument_list|,
name|TesseractOCRParser
operator|.
name|class
operator|.
name|toString
argument_list|()
argument_list|)
expr_stmt|;
block|}
name|PDF2XHTML
operator|.
name|process
argument_list|(
name|pdfDocument
argument_list|,
name|handler
argument_list|,
name|context
argument_list|,
name|metadata
argument_list|,
name|localConfig
argument_list|)
expr_stmt|;
block|}
block|}
block|}
catch|catch
parameter_list|(
name|InvalidPasswordException
name|e
parameter_list|)
block|{
name|metadata
operator|.
name|set
argument_list|(
name|PDF
operator|.
name|IS_ENCRYPTED
argument_list|,
literal|"true"
argument_list|)
expr_stmt|;
throw|throw
operator|new
name|EncryptedDocumentException
argument_list|(
name|e
argument_list|)
throw|;
block|}
finally|finally
block|{
if|if
condition|(
name|pdfDocument
operator|!=
literal|null
condition|)
block|{
name|pdfDocument
operator|.
name|close
argument_list|()
expr_stmt|;
block|}
block|}
block|}
specifier|private
name|String
name|getPassword
parameter_list|(
name|Metadata
name|metadata
parameter_list|,
name|ParseContext
name|context
parameter_list|)
block|{
name|String
name|password
init|=
literal|null
decl_stmt|;
comment|// Did they supply a new style Password Provider?
name|PasswordProvider
name|passwordProvider
init|=
name|context
operator|.
name|get
argument_list|(
name|PasswordProvider
operator|.
name|class
argument_list|)
decl_stmt|;
if|if
condition|(
name|passwordProvider
operator|!=
literal|null
condition|)
block|{
name|password
operator|=
name|passwordProvider
operator|.
name|getPassword
argument_list|(
name|metadata
argument_list|)
expr_stmt|;
block|}
comment|// Fall back on the old style metadata if set
if|if
condition|(
name|password
operator|==
literal|null
operator|&&
name|metadata
operator|.
name|get
argument_list|(
name|PASSWORD
argument_list|)
operator|!=
literal|null
condition|)
block|{
name|password
operator|=
name|metadata
operator|.
name|get
argument_list|(
name|PASSWORD
argument_list|)
expr_stmt|;
block|}
comment|// If no password is given, use an empty string as the default
if|if
condition|(
name|password
operator|==
literal|null
condition|)
block|{
name|password
operator|=
literal|""
expr_stmt|;
block|}
return|return
name|password
return|;
block|}
specifier|private
name|void
name|extractMetadata
parameter_list|(
name|PDDocument
name|document
parameter_list|,
name|Metadata
name|metadata
parameter_list|,
name|ParseContext
name|context
parameter_list|)
throws|throws
name|TikaException
block|{
comment|//first extract AccessPermissions
name|AccessPermission
name|ap
init|=
name|document
operator|.
name|getCurrentAccessPermission
argument_list|()
decl_stmt|;
name|metadata
operator|.
name|set
argument_list|(
name|AccessPermissions
operator|.
name|EXTRACT_FOR_ACCESSIBILITY
argument_list|,
name|Boolean
operator|.
name|toString
argument_list|(
name|ap
operator|.
name|canExtractForAccessibility
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|metadata
operator|.
name|set
argument_list|(
name|AccessPermissions
operator|.
name|EXTRACT_CONTENT
argument_list|,
name|Boolean
operator|.
name|toString
argument_list|(
name|ap
operator|.
name|canExtractContent
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|metadata
operator|.
name|set
argument_list|(
name|AccessPermissions
operator|.
name|ASSEMBLE_DOCUMENT
argument_list|,
name|Boolean
operator|.
name|toString
argument_list|(
name|ap
operator|.
name|canAssembleDocument
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|metadata
operator|.
name|set
argument_list|(
name|AccessPermissions
operator|.
name|FILL_IN_FORM
argument_list|,
name|Boolean
operator|.
name|toString
argument_list|(
name|ap
operator|.
name|canFillInForm
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|metadata
operator|.
name|set
argument_list|(
name|AccessPermissions
operator|.
name|CAN_MODIFY
argument_list|,
name|Boolean
operator|.
name|toString
argument_list|(
name|ap
operator|.
name|canModify
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|metadata
operator|.
name|set
argument_list|(
name|AccessPermissions
operator|.
name|CAN_MODIFY_ANNOTATIONS
argument_list|,
name|Boolean
operator|.
name|toString
argument_list|(
name|ap
operator|.
name|canModifyAnnotations
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|metadata
operator|.
name|set
argument_list|(
name|AccessPermissions
operator|.
name|CAN_PRINT
argument_list|,
name|Boolean
operator|.
name|toString
argument_list|(
name|ap
operator|.
name|canPrint
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|metadata
operator|.
name|set
argument_list|(
name|AccessPermissions
operator|.
name|CAN_PRINT_DEGRADED
argument_list|,
name|Boolean
operator|.
name|toString
argument_list|(
name|ap
operator|.
name|canPrintDegraded
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|document
operator|.
name|getDocumentCatalog
argument_list|()
operator|.
name|getLanguage
argument_list|()
operator|!=
literal|null
condition|)
block|{
name|metadata
operator|.
name|set
argument_list|(
name|TikaCoreProperties
operator|.
name|LANGUAGE
argument_list|,
name|document
operator|.
name|getDocumentCatalog
argument_list|()
operator|.
name|getLanguage
argument_list|()
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|document
operator|.
name|getDocumentCatalog
argument_list|()
operator|.
name|getAcroForm
argument_list|()
operator|!=
literal|null
operator|&&
name|document
operator|.
name|getDocumentCatalog
argument_list|()
operator|.
name|getAcroForm
argument_list|()
operator|.
name|getFields
argument_list|()
operator|!=
literal|null
operator|&&
name|document
operator|.
name|getDocumentCatalog
argument_list|()
operator|.
name|getAcroForm
argument_list|()
operator|.
name|getFields
argument_list|()
operator|.
name|size
argument_list|()
operator|>
literal|0
condition|)
block|{
name|metadata
operator|.
name|set
argument_list|(
name|PDF
operator|.
name|HAS_ACROFORM_FIELDS
argument_list|,
literal|"true"
argument_list|)
expr_stmt|;
block|}
name|PDMetadataExtractor
operator|.
name|extract
argument_list|(
name|document
operator|.
name|getDocumentCatalog
argument_list|()
operator|.
name|getMetadata
argument_list|()
argument_list|,
name|metadata
argument_list|,
name|context
argument_list|)
expr_stmt|;
name|PDDocumentInformation
name|info
init|=
name|document
operator|.
name|getDocumentInformation
argument_list|()
decl_stmt|;
name|metadata
operator|.
name|set
argument_list|(
name|PagedText
operator|.
name|N_PAGES
argument_list|,
name|document
operator|.
name|getNumberOfPages
argument_list|()
argument_list|)
expr_stmt|;
name|PDMetadataExtractor
operator|.
name|addMetadata
argument_list|(
name|metadata
argument_list|,
name|PDF
operator|.
name|DOC_INFO_TITLE
argument_list|,
name|info
operator|.
name|getTitle
argument_list|()
argument_list|)
expr_stmt|;
name|PDMetadataExtractor
operator|.
name|addMetadata
argument_list|(
name|metadata
argument_list|,
name|PDF
operator|.
name|DOC_INFO_CREATOR
argument_list|,
name|info
operator|.
name|getAuthor
argument_list|()
argument_list|)
expr_stmt|;
comment|//if this wasn't already set by xmp, use doc info
if|if
condition|(
name|metadata
operator|.
name|get
argument_list|(
name|TikaCoreProperties
operator|.
name|CREATOR
argument_list|)
operator|==
literal|null
condition|)
block|{
name|PDMetadataExtractor
operator|.
name|addMetadata
argument_list|(
name|metadata
argument_list|,
name|TikaCoreProperties
operator|.
name|CREATOR
argument_list|,
name|info
operator|.
name|getAuthor
argument_list|()
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|metadata
operator|.
name|get
argument_list|(
name|TikaCoreProperties
operator|.
name|TITLE
argument_list|)
operator|==
literal|null
condition|)
block|{
name|PDMetadataExtractor
operator|.
name|addMetadata
argument_list|(
name|metadata
argument_list|,
name|TikaCoreProperties
operator|.
name|TITLE
argument_list|,
name|info
operator|.
name|getTitle
argument_list|()
argument_list|)
expr_stmt|;
block|}
name|PDMetadataExtractor
operator|.
name|addMetadata
argument_list|(
name|metadata
argument_list|,
name|PDF
operator|.
name|DOC_INFO_CREATOR_TOOL
argument_list|,
name|info
operator|.
name|getCreator
argument_list|()
argument_list|)
expr_stmt|;
name|PDMetadataExtractor
operator|.
name|addMetadata
argument_list|(
name|metadata
argument_list|,
name|TikaCoreProperties
operator|.
name|CREATOR_TOOL
argument_list|,
name|info
operator|.
name|getCreator
argument_list|()
argument_list|)
expr_stmt|;
name|PDMetadataExtractor
operator|.
name|addMetadata
argument_list|(
name|metadata
argument_list|,
name|Office
operator|.
name|KEYWORDS
argument_list|,
name|info
operator|.
name|getKeywords
argument_list|()
argument_list|)
expr_stmt|;
name|PDMetadataExtractor
operator|.
name|addMetadata
argument_list|(
name|metadata
argument_list|,
name|PDF
operator|.
name|DOC_INFO_KEY_WORDS
argument_list|,
name|info
operator|.
name|getKeywords
argument_list|()
argument_list|)
expr_stmt|;
name|PDMetadataExtractor
operator|.
name|addMetadata
argument_list|(
name|metadata
argument_list|,
name|PDF
operator|.
name|DOC_INFO_PRODUCER
argument_list|,
name|info
operator|.
name|getProducer
argument_list|()
argument_list|)
expr_stmt|;
name|PDMetadataExtractor
operator|.
name|addMetadata
argument_list|(
name|metadata
argument_list|,
name|PDF
operator|.
name|DOC_INFO_SUBJECT
argument_list|,
name|info
operator|.
name|getSubject
argument_list|()
argument_list|)
expr_stmt|;
name|PDMetadataExtractor
operator|.
name|addMetadata
argument_list|(
name|metadata
argument_list|,
name|TikaCoreProperties
operator|.
name|SUBJECT
argument_list|,
name|info
operator|.
name|getKeywords
argument_list|()
argument_list|)
expr_stmt|;
name|PDMetadataExtractor
operator|.
name|addMetadata
argument_list|(
name|metadata
argument_list|,
name|TikaCoreProperties
operator|.
name|SUBJECT
argument_list|,
name|info
operator|.
name|getSubject
argument_list|()
argument_list|)
expr_stmt|;
name|PDMetadataExtractor
operator|.
name|addMetadata
argument_list|(
name|metadata
argument_list|,
name|OfficeOpenXMLCore
operator|.
name|SUBJECT
argument_list|,
name|info
operator|.
name|getSubject
argument_list|()
argument_list|)
expr_stmt|;
name|PDMetadataExtractor
operator|.
name|addMetadata
argument_list|(
name|metadata
argument_list|,
name|PDF
operator|.
name|DOC_INFO_TRAPPED
argument_list|,
name|info
operator|.
name|getTrapped
argument_list|()
argument_list|)
expr_stmt|;
name|Calendar
name|created
init|=
name|info
operator|.
name|getCreationDate
argument_list|()
decl_stmt|;
name|PDMetadataExtractor
operator|.
name|addMetadata
argument_list|(
name|metadata
argument_list|,
name|PDF
operator|.
name|DOC_INFO_CREATED
argument_list|,
name|created
argument_list|)
expr_stmt|;
name|PDMetadataExtractor
operator|.
name|addMetadata
argument_list|(
name|metadata
argument_list|,
name|TikaCoreProperties
operator|.
name|CREATED
argument_list|,
name|created
argument_list|)
expr_stmt|;
name|Calendar
name|modified
init|=
name|info
operator|.
name|getModificationDate
argument_list|()
decl_stmt|;
name|PDMetadataExtractor
operator|.
name|addMetadata
argument_list|(
name|metadata
argument_list|,
name|TikaCoreProperties
operator|.
name|MODIFIED
argument_list|,
name|modified
argument_list|)
expr_stmt|;
name|PDMetadataExtractor
operator|.
name|addMetadata
argument_list|(
name|metadata
argument_list|,
name|PDF
operator|.
name|DOC_INFO_MODIFICATION_DATE
argument_list|,
name|modified
argument_list|)
expr_stmt|;
comment|// All remaining metadata is custom
comment|// Copy this over as-is
name|List
argument_list|<
name|String
argument_list|>
name|handledMetadata
init|=
name|Arrays
operator|.
name|asList
argument_list|(
literal|"Author"
argument_list|,
literal|"Creator"
argument_list|,
literal|"CreationDate"
argument_list|,
literal|"ModDate"
argument_list|,
literal|"Keywords"
argument_list|,
literal|"Producer"
argument_list|,
literal|"Subject"
argument_list|,
literal|"Title"
argument_list|,
literal|"Trapped"
argument_list|)
decl_stmt|;
for|for
control|(
name|COSName
name|key
range|:
name|info
operator|.
name|getCOSObject
argument_list|()
operator|.
name|keySet
argument_list|()
control|)
block|{
name|String
name|name
init|=
name|key
operator|.
name|getName
argument_list|()
decl_stmt|;
if|if
condition|(
operator|!
name|handledMetadata
operator|.
name|contains
argument_list|(
name|name
argument_list|)
condition|)
block|{
name|PDMetadataExtractor
operator|.
name|addMetadata
argument_list|(
name|metadata
argument_list|,
name|name
argument_list|,
name|info
operator|.
name|getCOSObject
argument_list|()
operator|.
name|getDictionaryObject
argument_list|(
name|key
argument_list|)
argument_list|)
expr_stmt|;
name|PDMetadataExtractor
operator|.
name|addMetadata
argument_list|(
name|metadata
argument_list|,
name|PDF
operator|.
name|PDF_DOC_INFO_CUSTOM_PREFIX
operator|+
name|name
argument_list|,
name|info
operator|.
name|getCOSObject
argument_list|()
operator|.
name|getDictionaryObject
argument_list|(
name|key
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
comment|//try to get the various versions
comment|//Caveats:
comment|//    there is currently a fair amount of redundancy
comment|//    TikaCoreProperties.FORMAT can be multivalued
comment|//    There are also three potential pdf specific version keys: pdf:PDFVersion, pdfa:PDFVersion, pdf:PDFExtensionVersion
name|metadata
operator|.
name|set
argument_list|(
name|PDF
operator|.
name|PDF_VERSION
argument_list|,
name|Float
operator|.
name|toString
argument_list|(
name|document
operator|.
name|getDocument
argument_list|()
operator|.
name|getVersion
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|metadata
operator|.
name|add
argument_list|(
name|TikaCoreProperties
operator|.
name|FORMAT
operator|.
name|getName
argument_list|()
argument_list|,
name|MEDIA_TYPE
operator|.
name|toString
argument_list|()
operator|+
literal|"; version="
operator|+
name|Float
operator|.
name|toString
argument_list|(
name|document
operator|.
name|getDocument
argument_list|()
operator|.
name|getVersion
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
comment|//TODO: Let's try to move this into PDFBox.
comment|//Attempt to determine Adobe extension level, if present:
name|COSDictionary
name|root
init|=
name|document
operator|.
name|getDocumentCatalog
argument_list|()
operator|.
name|getCOSObject
argument_list|()
decl_stmt|;
name|COSDictionary
name|extensions
init|=
operator|(
name|COSDictionary
operator|)
name|root
operator|.
name|getDictionaryObject
argument_list|(
name|COSName
operator|.
name|getPDFName
argument_list|(
literal|"Extensions"
argument_list|)
argument_list|)
decl_stmt|;
if|if
condition|(
name|extensions
operator|!=
literal|null
condition|)
block|{
for|for
control|(
name|COSName
name|extName
range|:
name|extensions
operator|.
name|keySet
argument_list|()
control|)
block|{
comment|// If it's an Adobe one, interpret it to determine the extension level:
if|if
condition|(
name|extName
operator|.
name|equals
argument_list|(
name|COSName
operator|.
name|getPDFName
argument_list|(
literal|"ADBE"
argument_list|)
argument_list|)
condition|)
block|{
name|COSDictionary
name|adobeExt
init|=
operator|(
name|COSDictionary
operator|)
name|extensions
operator|.
name|getDictionaryObject
argument_list|(
name|extName
argument_list|)
decl_stmt|;
if|if
condition|(
name|adobeExt
operator|!=
literal|null
condition|)
block|{
name|String
name|baseVersion
init|=
name|adobeExt
operator|.
name|getNameAsString
argument_list|(
name|COSName
operator|.
name|getPDFName
argument_list|(
literal|"BaseVersion"
argument_list|)
argument_list|)
decl_stmt|;
name|int
name|el
init|=
name|adobeExt
operator|.
name|getInt
argument_list|(
name|COSName
operator|.
name|getPDFName
argument_list|(
literal|"ExtensionLevel"
argument_list|)
argument_list|)
decl_stmt|;
comment|//-1 is sentinel value that something went wrong in getInt
if|if
condition|(
name|el
operator|!=
operator|-
literal|1
condition|)
block|{
name|metadata
operator|.
name|set
argument_list|(
name|PDF
operator|.
name|PDF_EXTENSION_VERSION
argument_list|,
name|baseVersion
operator|+
literal|" Adobe Extension Level "
operator|+
name|el
argument_list|)
expr_stmt|;
name|metadata
operator|.
name|add
argument_list|(
name|TikaCoreProperties
operator|.
name|FORMAT
operator|.
name|getName
argument_list|()
argument_list|,
name|MEDIA_TYPE
operator|.
name|toString
argument_list|()
operator|+
literal|"; version=\""
operator|+
name|baseVersion
operator|+
literal|" Adobe Extension Level "
operator|+
name|el
operator|+
literal|"\""
argument_list|)
expr_stmt|;
block|}
block|}
block|}
else|else
block|{
comment|// WARN that there is an Extension, but it's not Adobe's, and so is a 'new' format'.
name|metadata
operator|.
name|set
argument_list|(
literal|"pdf:foundNonAdobeExtensionName"
argument_list|,
name|extName
operator|.
name|getName
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
block|}
block|}
specifier|private
name|boolean
name|hasXFA
parameter_list|(
name|PDDocument
name|pdDocument
parameter_list|)
block|{
return|return
name|pdDocument
operator|.
name|getDocumentCatalog
argument_list|()
operator|!=
literal|null
operator|&&
name|pdDocument
operator|.
name|getDocumentCatalog
argument_list|()
operator|.
name|getAcroForm
argument_list|()
operator|!=
literal|null
operator|&&
name|pdDocument
operator|.
name|getDocumentCatalog
argument_list|()
operator|.
name|getAcroForm
argument_list|()
operator|.
name|hasXFA
argument_list|()
return|;
block|}
specifier|private
name|boolean
name|shouldHandleXFAOnly
parameter_list|(
name|boolean
name|hasXFA
parameter_list|,
name|PDFParserConfig
name|config
parameter_list|)
block|{
return|return
name|config
operator|.
name|getIfXFAExtractOnlyXFA
argument_list|()
operator|&&
name|hasXFA
return|;
block|}
specifier|private
name|void
name|handleXFAOnly
parameter_list|(
name|PDDocument
name|pdDocument
parameter_list|,
name|ContentHandler
name|handler
parameter_list|,
name|Metadata
name|metadata
parameter_list|,
name|ParseContext
name|context
parameter_list|)
throws|throws
name|SAXException
throws|,
name|IOException
throws|,
name|TikaException
block|{
name|XFAExtractor
name|ex
init|=
operator|new
name|XFAExtractor
argument_list|()
decl_stmt|;
name|XHTMLContentHandler
name|xhtml
init|=
operator|new
name|XHTMLContentHandler
argument_list|(
name|handler
argument_list|,
name|metadata
argument_list|)
decl_stmt|;
name|xhtml
operator|.
name|startDocument
argument_list|()
expr_stmt|;
try|try
init|(
name|InputStream
name|is
init|=
operator|new
name|ByteArrayInputStream
argument_list|(
name|pdDocument
operator|.
name|getDocumentCatalog
argument_list|()
operator|.
name|getAcroForm
argument_list|()
operator|.
name|getXFA
argument_list|()
operator|.
name|getBytes
argument_list|()
argument_list|)
init|)
block|{
name|ex
operator|.
name|extract
argument_list|(
name|is
argument_list|,
name|xhtml
argument_list|,
name|metadata
argument_list|,
name|context
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|XMLStreamException
name|e
parameter_list|)
block|{
throw|throw
operator|new
name|TikaException
argument_list|(
literal|"XML error in XFA"
argument_list|,
name|e
argument_list|)
throw|;
block|}
name|xhtml
operator|.
name|endDocument
argument_list|()
expr_stmt|;
block|}
specifier|public
name|PDFParserConfig
name|getPDFParserConfig
parameter_list|()
block|{
return|return
name|defaultConfig
return|;
block|}
specifier|public
name|void
name|setPDFParserConfig
parameter_list|(
name|PDFParserConfig
name|config
parameter_list|)
block|{
name|this
operator|.
name|defaultConfig
operator|=
name|config
expr_stmt|;
block|}
comment|/**      * @see #setEnableAutoSpace(boolean)      * @deprecated use {@link #getPDFParserConfig()}      */
specifier|public
name|boolean
name|getEnableAutoSpace
parameter_list|()
block|{
return|return
name|defaultConfig
operator|.
name|getEnableAutoSpace
argument_list|()
return|;
block|}
comment|/**      * If true (the default), the parser should estimate      * where spaces should be inserted between words.  For      * many PDFs this is necessary as they do not include      * explicit whitespace characters.      *      * @deprecated use {@link #setPDFParserConfig(PDFParserConfig)}      */
specifier|public
name|void
name|setEnableAutoSpace
parameter_list|(
name|boolean
name|v
parameter_list|)
block|{
name|defaultConfig
operator|.
name|setEnableAutoSpace
argument_list|(
name|v
argument_list|)
expr_stmt|;
block|}
comment|/**      * If true, text in annotations will be extracted.      *      * @deprecated use {@link #getPDFParserConfig()}      */
specifier|public
name|boolean
name|getExtractAnnotationText
parameter_list|()
block|{
return|return
name|defaultConfig
operator|.
name|getExtractAnnotationText
argument_list|()
return|;
block|}
comment|/**      * If true (the default), text in annotations will be      * extracted.      *      * @deprecated use {@link #setPDFParserConfig(PDFParserConfig)}      */
specifier|public
name|void
name|setExtractAnnotationText
parameter_list|(
name|boolean
name|v
parameter_list|)
block|{
name|defaultConfig
operator|.
name|setExtractAnnotationText
argument_list|(
name|v
argument_list|)
expr_stmt|;
block|}
comment|/**      * @see #setSuppressDuplicateOverlappingText(boolean)      * @deprecated use {@link #getPDFParserConfig()}      */
specifier|public
name|boolean
name|getSuppressDuplicateOverlappingText
parameter_list|()
block|{
return|return
name|defaultConfig
operator|.
name|getSuppressDuplicateOverlappingText
argument_list|()
return|;
block|}
comment|/**      * If true, the parser should try to remove duplicated      * text over the same region.  This is needed for some      * PDFs that achieve bolding by re-writing the same      * text in the same area.  Note that this can      * slow down extraction substantially (PDFBOX-956) and      * sometimes remove characters that were not in fact      * duplicated (PDFBOX-1155).  By default this is disabled.      *      * @deprecated use {@link #setPDFParserConfig(PDFParserConfig)}      */
specifier|public
name|void
name|setSuppressDuplicateOverlappingText
parameter_list|(
name|boolean
name|v
parameter_list|)
block|{
name|defaultConfig
operator|.
name|setSuppressDuplicateOverlappingText
argument_list|(
name|v
argument_list|)
expr_stmt|;
block|}
comment|/**      * @see #setSortByPosition(boolean)      * @deprecated use {@link #getPDFParserConfig()}      */
specifier|public
name|boolean
name|getSortByPosition
parameter_list|()
block|{
return|return
name|defaultConfig
operator|.
name|getSortByPosition
argument_list|()
return|;
block|}
comment|/**      * If true, sort text tokens by their x/y position      * before extracting text.  This may be necessary for      * some PDFs (if the text tokens are not rendered "in      * order"), while for other PDFs it can produce the      * wrong result (for example if there are 2 columns,      * the text will be interleaved).  Default is false.      *      * @deprecated use {@link #setPDFParserConfig(PDFParserConfig)}      */
annotation|@
name|Field
specifier|public
name|void
name|setSortByPosition
parameter_list|(
name|boolean
name|v
parameter_list|)
block|{
name|defaultConfig
operator|.
name|setSortByPosition
argument_list|(
name|v
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Field
specifier|public
name|void
name|setOcrStrategy
parameter_list|(
name|String
name|ocrStrategyString
parameter_list|)
block|{
name|defaultConfig
operator|.
name|setOcrStrategy
argument_list|(
name|ocrStrategyString
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Field
specifier|public
name|void
name|setOcrImageType
parameter_list|(
name|String
name|imageType
parameter_list|)
block|{
name|defaultConfig
operator|.
name|setOcrImageType
argument_list|(
name|imageType
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Field
name|void
name|setOcrDPI
parameter_list|(
name|int
name|dpi
parameter_list|)
block|{
name|defaultConfig
operator|.
name|setOcrDPI
argument_list|(
name|dpi
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Field
name|void
name|setOcrImageQuality
parameter_list|(
name|float
name|imageQuality
parameter_list|)
block|{
name|defaultConfig
operator|.
name|setOcrImageQuality
argument_list|(
name|imageQuality
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Field
name|void
name|setOcrImageFormatName
parameter_list|(
name|String
name|formatName
parameter_list|)
block|{
name|defaultConfig
operator|.
name|setOcrImageFormatName
argument_list|(
name|formatName
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Field
name|void
name|setExtractBookmarksText
parameter_list|(
name|boolean
name|extractBookmarksText
parameter_list|)
block|{
name|defaultConfig
operator|.
name|setExtractBookmarksText
argument_list|(
name|extractBookmarksText
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Field
name|void
name|setExtractInlineImages
parameter_list|(
name|boolean
name|extractInlineImages
parameter_list|)
block|{
name|defaultConfig
operator|.
name|setExtractInlineImages
argument_list|(
name|extractInlineImages
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Field
name|void
name|setCatchIntermediateExceptions
parameter_list|(
name|boolean
name|catchIntermediateExceptions
parameter_list|)
block|{
name|defaultConfig
operator|.
name|setCatchIntermediateIOExceptions
argument_list|(
name|catchIntermediateExceptions
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Field
name|void
name|setExtractAcroFormContent
parameter_list|(
name|boolean
name|extractAcroFormContent
parameter_list|)
block|{
name|defaultConfig
operator|.
name|setExtractAcroFormContent
argument_list|(
name|extractAcroFormContent
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Field
name|void
name|setIfXFAExtractOnlyXFA
parameter_list|(
name|boolean
name|ifXFAExtractOnlyXFA
parameter_list|)
block|{
name|defaultConfig
operator|.
name|setIfXFAExtractOnlyXFA
argument_list|(
name|ifXFAExtractOnlyXFA
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Field
name|void
name|setAllowExtractionForAccessibility
parameter_list|(
name|boolean
name|allowExtractionForAccessibility
parameter_list|)
block|{
name|defaultConfig
operator|.
name|setAccessChecker
argument_list|(
operator|new
name|AccessChecker
argument_list|(
name|allowExtractionForAccessibility
argument_list|)
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Field
name|void
name|setExtractUniqueInlineImagesOnly
parameter_list|(
name|boolean
name|extractUniqueInlineImagesOnly
parameter_list|)
block|{
name|defaultConfig
operator|.
name|setExtractUniqueInlineImagesOnly
argument_list|(
name|extractUniqueInlineImagesOnly
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Field
name|void
name|setExtractActions
parameter_list|(
name|boolean
name|extractActions
parameter_list|)
block|{
name|defaultConfig
operator|.
name|setExtractActions
argument_list|(
name|extractActions
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Field
name|void
name|setExtractFontNames
parameter_list|(
name|boolean
name|extractFontNames
parameter_list|)
block|{
name|defaultConfig
operator|.
name|setExtractFontNames
argument_list|(
name|extractFontNames
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Field
name|void
name|setSetKCMS
parameter_list|(
name|boolean
name|setKCMS
parameter_list|)
block|{
name|defaultConfig
operator|.
name|setSetKCMS
argument_list|(
name|setKCMS
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Field
name|void
name|setDetectAngles
parameter_list|(
name|boolean
name|detectAngles
parameter_list|)
block|{
name|defaultConfig
operator|.
name|setDetectAngles
argument_list|(
name|detectAngles
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Field
name|void
name|setInitializableProblemHander
parameter_list|(
name|String
name|name
parameter_list|)
block|{
if|if
condition|(
literal|"ignore"
operator|.
name|equals
argument_list|(
name|name
argument_list|)
condition|)
block|{
name|setInitializableProblemHandler
argument_list|(
name|InitializableProblemHandler
operator|.
name|IGNORE
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
literal|"info"
operator|.
name|equalsIgnoreCase
argument_list|(
name|name
argument_list|)
condition|)
block|{
name|setInitializableProblemHandler
argument_list|(
name|InitializableProblemHandler
operator|.
name|INFO
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
literal|"warn"
operator|.
name|equalsIgnoreCase
argument_list|(
name|name
argument_list|)
condition|)
block|{
name|setInitializableProblemHandler
argument_list|(
name|InitializableProblemHandler
operator|.
name|WARN
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
literal|"throw"
operator|.
name|equalsIgnoreCase
argument_list|(
name|name
argument_list|)
condition|)
block|{
name|setInitializableProblemHandler
argument_list|(
name|InitializableProblemHandler
operator|.
name|THROW
argument_list|)
expr_stmt|;
block|}
block|}
specifier|public
name|void
name|setInitializableProblemHandler
parameter_list|(
name|InitializableProblemHandler
name|initializableProblemHandler
parameter_list|)
block|{
name|this
operator|.
name|initializableProblemHandler
operator|=
name|initializableProblemHandler
expr_stmt|;
block|}
annotation|@
name|Field
specifier|public
name|void
name|setDropThreshold
parameter_list|(
name|float
name|dropThreshold
parameter_list|)
block|{
name|defaultConfig
operator|.
name|setDropThreshold
argument_list|(
name|dropThreshold
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Field
specifier|public
name|void
name|setMaxMainMemoryBytes
parameter_list|(
name|long
name|maxMainMemoryBytes
parameter_list|)
block|{
name|defaultConfig
operator|.
name|setMaxMainMemoryBytes
argument_list|(
name|maxMainMemoryBytes
argument_list|)
expr_stmt|;
block|}
comment|/**      * This is a no-op.  There is no need to initialize multiple fields.      * The regular field loading should happen without this.      *      * @param params params to use for initialization      * @throws TikaConfigException      */
annotation|@
name|Override
specifier|public
name|void
name|initialize
parameter_list|(
name|Map
argument_list|<
name|String
argument_list|,
name|Param
argument_list|>
name|params
parameter_list|)
throws|throws
name|TikaConfigException
block|{
comment|//no-op
block|}
annotation|@
name|Override
specifier|public
name|void
name|checkInitialization
parameter_list|(
name|InitializableProblemHandler
name|handler
parameter_list|)
throws|throws
name|TikaConfigException
block|{
comment|//only check for these libraries once!
if|if
condition|(
name|HAS_WARNED
condition|)
block|{
return|return;
block|}
synchronized|synchronized
init|(
name|LOCK
init|)
block|{
if|if
condition|(
name|HAS_WARNED
condition|)
block|{
return|return;
block|}
name|StringBuilder
name|sb
init|=
operator|new
name|StringBuilder
argument_list|()
decl_stmt|;
try|try
block|{
name|Class
operator|.
name|forName
argument_list|(
literal|"com.github.jaiimageio.impl.plugins.tiff.TIFFImageWriter"
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|ClassNotFoundException
name|e
parameter_list|)
block|{
name|sb
operator|.
name|append
argument_list|(
literal|"TIFFImageWriter not loaded. tiff files will not be processed\n"
argument_list|)
expr_stmt|;
name|sb
operator|.
name|append
argument_list|(
literal|"See https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io\n"
argument_list|)
expr_stmt|;
name|sb
operator|.
name|append
argument_list|(
literal|"for optional dependencies.\n"
argument_list|)
expr_stmt|;
block|}
try|try
block|{
name|Class
operator|.
name|forName
argument_list|(
literal|"com.github.jaiimageio.jpeg2000.impl.J2KImageReader"
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|ClassNotFoundException
name|e
parameter_list|)
block|{
name|sb
operator|.
name|append
argument_list|(
literal|"J2KImageReader not loaded. JPEG2000 files will not be processed.\n"
argument_list|)
expr_stmt|;
name|sb
operator|.
name|append
argument_list|(
literal|"See https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io\n"
argument_list|)
expr_stmt|;
name|sb
operator|.
name|append
argument_list|(
literal|"for optional dependencies.\n"
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|sb
operator|.
name|length
argument_list|()
operator|>
literal|0
condition|)
block|{
name|InitializableProblemHandler
name|localInitializableProblemHandler
init|=
operator|(
name|initializableProblemHandler
operator|==
literal|null
operator|)
condition|?
name|handler
else|:
name|initializableProblemHandler
decl_stmt|;
name|localInitializableProblemHandler
operator|.
name|handleInitializableProblem
argument_list|(
literal|"org.apache.tika.parsers.PDFParser"
argument_list|,
name|sb
operator|.
name|toString
argument_list|()
argument_list|)
expr_stmt|;
block|}
name|HAS_WARNED
operator|=
literal|true
expr_stmt|;
block|}
block|}
block|}
end_class

end_unit

