begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|server
package|;
end_package

begin_class
specifier|public
class|class
name|ServerTimeouts
block|{
comment|/*     TODO: integrate these settings:      * Number of milliseconds to wait to start child process.     public static final long DEFAULT_CHILD_PROCESS_STARTUP_MILLIS = 60000;       * Maximum number of milliseconds to wait to shutdown child process to allow      * for current parses to complete.     public static final long DEFAULT_CHILD_PROCESS_SHUTDOWN_MILLIS = 30000;      private long childProcessStartupMillis = DEFAULT_CHILD_PROCESS_STARTUP_MILLIS;      private long childProcessShutdownMillis = DEFAULT_CHILD_PROCESS_SHUTDOWN_MILLIS;       */
comment|/**      * If the child doesn't receive a ping or the parent doesn't      * hear back from a ping in this amount of time, kill and restart the child.      */
specifier|public
specifier|static
specifier|final
name|long
name|DEFAULT_PING_TIMEOUT_MILLIS
init|=
literal|30000
decl_stmt|;
comment|/**      * How often should the parent try to ping the child to check status      */
specifier|public
specifier|static
specifier|final
name|long
name|DEFAULT_PING_PULSE_MILLIS
init|=
literal|500
decl_stmt|;
comment|/**      * Number of milliseconds to wait per server task (parse, detect, unpack, translate,      * etc.) before timing out and shutting down the child process.      */
specifier|public
specifier|static
specifier|final
name|long
name|DEFAULT_TASK_TIMEOUT_MILLIS
init|=
literal|120000
decl_stmt|;
specifier|private
name|long
name|taskTimeoutMillis
init|=
name|DEFAULT_TASK_TIMEOUT_MILLIS
decl_stmt|;
specifier|private
name|long
name|pingTimeoutMillis
init|=
name|DEFAULT_PING_TIMEOUT_MILLIS
decl_stmt|;
specifier|private
name|long
name|pingPulseMillis
init|=
name|DEFAULT_PING_PULSE_MILLIS
decl_stmt|;
comment|/**      * How long to wait for a task before shutting down the child server process      * and restarting it.      * @return      */
specifier|public
name|long
name|getTaskTimeoutMillis
parameter_list|()
block|{
return|return
name|taskTimeoutMillis
return|;
block|}
comment|/**      *      * @param taskTimeoutMillis number of milliseconds to allow per task      *                          (parse, detection, unzipping, etc.)      */
specifier|public
name|void
name|setTaskTimeoutMillis
parameter_list|(
name|long
name|taskTimeoutMillis
parameter_list|)
block|{
name|this
operator|.
name|taskTimeoutMillis
operator|=
name|taskTimeoutMillis
expr_stmt|;
block|}
specifier|public
name|long
name|getPingTimeoutMillis
parameter_list|()
block|{
return|return
name|pingTimeoutMillis
return|;
block|}
comment|/**      *      * @param pingTimeoutMillis if the parent doesn't receive a response      *                          in this amount of time, or      *                          if the child doesn't receive a ping      *                          in this amount of time, restart the child process      */
specifier|public
name|void
name|setPingTimeoutMillis
parameter_list|(
name|long
name|pingTimeoutMillis
parameter_list|)
block|{
name|this
operator|.
name|pingTimeoutMillis
operator|=
name|pingTimeoutMillis
expr_stmt|;
block|}
specifier|public
name|long
name|getPingPulseMillis
parameter_list|()
block|{
return|return
name|pingPulseMillis
return|;
block|}
comment|/**      *      * @param pingPulseMillis how often to test that the parent and/or child is alive      */
specifier|public
name|void
name|setPingPulseMillis
parameter_list|(
name|long
name|pingPulseMillis
parameter_list|)
block|{
name|this
operator|.
name|pingPulseMillis
operator|=
name|pingPulseMillis
expr_stmt|;
block|}
block|}
end_class

end_unit

