begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|parser
operator|.
name|microsoft
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|InputStream
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|poi
operator|.
name|poifs
operator|.
name|filesystem
operator|.
name|POIFSFileSystem
import|;
end_import

begin_comment
comment|/**  * Power point parser  */
end_comment

begin_class
specifier|public
class|class
name|PowerPointParser
extends|extends
name|OfficeParser
block|{
comment|/**      *  Name of a PowerPoint document within a POIFS file system      */
specifier|private
specifier|static
specifier|final
name|String
name|POWERPOINT
init|=
literal|"PowerPoint Document"
decl_stmt|;
specifier|protected
name|String
name|getContentType
parameter_list|()
block|{
return|return
literal|"application/vnd.ms-powerpoint"
return|;
block|}
specifier|protected
name|void
name|extractText
parameter_list|(
name|POIFSFileSystem
name|filesystem
parameter_list|,
name|Appendable
name|builder
parameter_list|)
throws|throws
name|IOException
block|{
name|InputStream
name|stream
init|=
name|filesystem
operator|.
name|createDocumentInputStream
argument_list|(
name|POWERPOINT
argument_list|)
decl_stmt|;
try|try
block|{
operator|new
name|PowerPointExtractor
argument_list|(
name|builder
argument_list|)
operator|.
name|extract
argument_list|(
name|stream
argument_list|)
expr_stmt|;
block|}
finally|finally
block|{
name|stream
operator|.
name|close
argument_list|()
expr_stmt|;
block|}
block|}
block|}
end_class

end_unit

